site_name: First Documentation

theme:
  name: 'material'

plugins:
  - mkdocstrings

nav:
  - My First Documentation: index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md